#!/bin/bash

location=/media/pi/My_Files

#Start bitcoin
echo -e "\e[34mBitcoin latest block...\e[0m"
echo -e `bitcoin-cli -datadir=$location/bitcoin getblockcount` of `wget -O - http://blockchain.info/q/getblockcount 2>/dev/null`

echo -e "\e[34mEthereum latest action...\e[0m"
tail -1 ~/geth-log


